name: Update IPTV

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python3 scripts/fetch.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

        git add README.md output/info.txt output/result.m3u output/result.txt || true

        git commit -m "Auto update IPTV files and README" || echo "No changes to commit"

        git push origin main
